### ISSUE TITLE
Fungi sequences

### ISSUE THREAD

**Issue by bsmoda** [SegataLab/repophlan#2]
Hello!

In the readme.txt, there is a mention of a script for downloading fungi sequences from NBCI (repophlan_get_euks.py), but this script is not available in the repository. I've also checked the paper that uses the RepoPlhan (http://www.nature.com/articles/s41586-020-2095-1), but they didn't mention fungi in the database. The repophlan_get_microbes.py is getting the fungi information, or do you remove them from the database?

Thank you!

**Comment by fbeghini** [comment]
Yes, repophlan_get_microbes retrieves genomes for both prokaryotes and fungi
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ

**Comment by bsmoda** [comment]
Thank you for your answer. Now I have another doubt regarding the repophlan_get_microbes script, in the code line below this list contains the phylum Chytridiomycota that belongs to the Fungi kingdom. I actually didn't understand 
39, 393
      toescl = ["p__Annelida", "p__Arthropoda", "p__Chordata", "p__Chytridiomycota", "p__Echinodermata", "p__Hemichordata",
      if not line_d['taxonomy'] or line_d['taxonomy'].count("|") < 1 or line_d['taxonomy'].split('|')[1] in toescl:
